### ISSUE TITLE
Min-height 100vh - Mobile devices

### ISSUE THREAD

**Issue by IOIIOOIO** [Andy-set-studio/modern-css-reset#15] opened 2019-10-22 09:13 UTC
I'm just wondering about your choice of setting `body` to `min-height: 100vh` and the implications it has for mobile devices?

Here's an article that helped me recently with an issue I was having on iPhone:

https://chanind.github.io/javascript/2019/09/28/avoid-100vh-on-mobile-web.html

**Comment by Andy-set-studio** [comment] 2019-10-23 09:38
Howdy, this is a duplicate of #4 🙂

**Closed as completed by Andy-set-studio** 2019-10-23 09:38 UTC
Labels: duplicate
